### ISSUE TITLE
Issue with bmptk++ and Windows path separators

### ISSUE THREAD

**Issue by cjsmeele** [R2D2-2017/R2D2-2017#3]
As reported by @JeroenKok by e-mail:
```
C:\Users\jeroen\Documents\gitkraken\R2D2-2017 [feat-gas]> python3 bmptk++.py generate
Generating build directory for modules\GAS\.bmptkpp...
Traceback (most recent call last):
  File "bmptk++.py", line 152, in <module>
    args.func(args)
  File "bmptk++.py", line 100, in generate
    generate_one(filename.replace("/.bmptkpp", ""), args.override_generator)
  File "bmptk++.py", line 78, in generate_one
    with open(path + '/.bmptkpp', 'r') as bmptkpp:
FileNotFoundError: [Errno 2] No such file or directory: 'modules\\GAS\\.bmptkpp/.bmptkpp'
```
This seems to be caused by the `filename.replace` call which only looks for `/` path separators.

**Comment by ghost** [comment]
At line 99 and 100 of bmtpk++.py , replaced the 2 and 1 '/' with '\\' respectively seems to work for me. Don't know about Linux &/ others.
